### ISSUE TITLE
index.php directory lib instead of libs

### ISSUE THREAD

**Issue by rogue94** [rolfjoseph/OpenWebsoccer#1]
code of index.php is showing include of "include('./libs/iosec/iosec.php');"

instread it has to be lib and not libs since the default directory is "lib"

**Comment by rolfjoseph** [comment]
I know ist´s fixed with folows realeases at http://openwebsoccer.de/owncloud/OpenWebsoccer.2016.4.30.exe, but not on github yet. The next github refresh comes with more of refreshing code.
